service: task-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    ACCESS_KEY_ID: "AKIAVUHZY32GABKXCHVY"
    ACCESS_KEY: "8gYrMogrU9sQPsYxZdbgMLV1RroXYnLW1Pnu1tXC"
    REGION: "eu-central-1"
    POSTGRES_USER: "wardsprod"
    POSTGRES_DB: "postgres"
    POSTGRES_PASSWORD: "02hkM2EpHYFeBvZCkvea"
    POSTGRES_HOST: "wards-prod.c1kcykenvknf.eu-central-1.rds.amazonaws.com"
    ACTIVE_PROFILE: "production"

functions:
  MINUTE_1:
    handler: src/functions/processTasks.run
    events:
      - schedule: rate(1 minute)
  MINUTE_2:
    handler: src/functions/processTasks.run
    events:
      - schedule: rate(2 minutes)
  MINUTE_3:
    handler: src/functions/processTasks.run
    events:
      - schedule: rate(3 minutes)
  MINUTE_5:
    handler: src/functions/processTasks.run
    events:
      - schedule: rate(5 minutes)
  MINUTE_10:
    handler: src/functions/processTasks.run
    events:
      - schedule: rate(10 minutes)
  MINUTE_15:
    handler: src/functions/processTasks.run
    events:
      - schedule: rate(15 minutes)
  MINUTE_30:
    handler: src/functions/processTasks.run
    events:
      - schedule: rate(30 minutes)

plugins:
  - serverless-lift
  - serverless-plugin-typescript
